# 이 워크플로우는 unrated 폴더 파일을 지정 레벨 폴더로 이동합니다.

name: Move unrated # GitHub Actions 탭에서 확인할 수 있는 액션 이름

on: # jobs가 실행되어야 하는 상황 정의
  push:
    branches: [ "main" ] # main 브랜치에 push가 발생했을 때
  pull_request:

jobs: # 실제 실행될 내용
  build:
    runs-on: ubuntu-latest # 빌드 환경
    steps:
    - uses: actions/checkout@v3 # checkout
    - name: Set up Python 3.10 
      uses: actions/setup-python@v3 # setup-python
      with:
        python-version: "3.10" # 3.10버전 파이썬 사용
    - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run move unrated # 2) unrated 폴더 이동
      run: |
        git mv 프로그래머스/unrated/* 프로그래머스/lv1/
    - name: Commit changes # 3) 추가된 파일 commit
      run: |
        git config --global user.name 'be4rpooh02' # 유저명
        git config --global user.email 'be4rpooh02@gmail.com' # 유저 이메일
        git add -A
        git commit -am "Move from unrated to lv1" # 커밋 메시지
    - name: Push changes # 4) 메인에 푸시
      run: |
        git push
